<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Kal-El" failures="0" tests="8" name="com.shield.tests.service.UserServiceMockitoTest" time="0.008" errors="1" timestamp="2022-01-12T17:19:23 CST" skipped="0">
  <testcase classname="com.shield.tests.service.UserServiceMockitoTest" name="getAllUsersServiceMock" time="0.001"/>
  <system-out/>
  <testcase classname="com.shield.tests.service.UserServiceMockitoTest" name="getUserServiceByIdSadMock" time="0.002"/>
  <system-out/>
  <testcase classname="com.shield.tests.service.UserServiceMockitoTest" name="checkUsernameAndPasswordServiceSadPasswordMock" time="0.001"/>
  <system-out/>
  <testcase classname="com.shield.tests.service.UserServiceMockitoTest" name="getUserServiceByIdMock" time="0.001"/>
  <system-out/>
  <testcase classname="com.shield.tests.service.UserServiceMockitoTest" name="checkUsernameAndPasswordServiceSadUsernameMock" time="0.000"/>
  <system-out/>
  <testcase classname="com.shield.tests.service.UserServiceMockitoTest" name="checkUsernameAndPasswordServiceMock" time="0.001"/>
  <system-out/>
  <testcase classname="com.shield.tests.service.UserServiceMockitoTest" name="getAllClaimsByUserIdServiceMock" time="0.001"/>
  <system-out/>
  <testcase classname="com.shield.tests.service.UserServiceMockitoTest" name="createUserServiceMock" time="0.001">
    <error message="Username is already taken" type="com.shield.customexceptions.UsernameAlreadyExists">
      <![CDATA[com.shield.customexceptions.UsernameAlreadyExists: Username is already taken
at com.shield.services.user.UserServicesImp.createUser(UserServicesImp.java:47)
at com.shield.tests.service.UserServiceMockitoTest.createUserServiceMock(UserServiceMockitoTest.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </error>
  </testcase> <!-- createUserServiceMock -->
  <system-out/>
</testsuite> <!-- com.shield.tests.service.UserServiceMockitoTest -->
